// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @weatherstations/climate
const encoding0 = {
  preencode(state, m) {
    c.date.preencode(state, m.timestamp)
    c.float64.preencode(state, m.temperature)
    c.uint.preencode(state, m.humidity)
    c.string.preencode(state, m.name)
  },
  encode(state, m) {
    c.date.encode(state, m.timestamp)
    c.float64.encode(state, m.temperature)
    c.uint.encode(state, m.humidity)
    c.string.encode(state, m.name)
  },
  decode(state) {
    const r0 = c.date.decode(state)
    const r1 = c.float64.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.string.decode(state)

    return {
      timestamp: r0,
      temperature: r1,
      humidity: r2,
      name: r3
    }
  }
}

// @weatherstations/wind
const encoding1 = {
  preencode(state, m) {
    c.date.preencode(state, m.timestamp)
    c.float64.preencode(state, m.speed)
    c.string.preencode(state, m.direction)
  },
  encode(state, m) {
    c.date.encode(state, m.timestamp)
    c.float64.encode(state, m.speed)
    c.string.encode(state, m.direction)
  },
  decode(state) {
    const r0 = c.date.decode(state)
    const r1 = c.float64.decode(state)
    const r2 = c.string.decode(state)

    return {
      timestamp: r0,
      speed: r1,
      direction: r2
    }
  }
}

// @weatherstations/station
const encoding2 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.float64.preencode(state, m.lat)
    c.float64.preencode(state, m.lon)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
    c.float64.encode(state, m.lat)
    c.float64.encode(state, m.lon)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.float64.decode(state)
    const r2 = c.float64.decode(state)

    return {
      name: r0,
      lat: r1,
      lon: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@weatherstations/climate':
      return encoding0
    case '@weatherstations/wind':
      return encoding1
    case '@weatherstations/station':
      return encoding2
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
